name: toNeko
version: '0.0.2'
main: com.crystalneko.toneko.ToNeko
api-version: '1.20'
commands:
  toneko:
    usage: /toneko
    aliases: [cnk,tocat]
permissions:
  toneko.command:
    default: true
  toneko.command.item:
    default: true